<a href="https://colab.research.google.com/github/KaustubhSN12/Github_Session_1/blob/main/Assigment_2_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignent 2_ Date: 22/07/2025

##Subject : Machine Learning

##Basic to Advanced Numpy:


Create a 1D NumPy array of numbers from 0 to 9.

Create an array of 10 zeros.

Create an array of 10 ones.

Create an array of 10 fives.

Create an array of even integers from 10 to 50.

Create a 3x3 identity matrix.

Generate an array of 20 linearly spaced numbers between 0 and 1.

Create a 5x5 matrix with values from 1 to 25.

Create a 3x3 matrix with random integers from 1 to 10.

Get the shape and size of an array.

Change the data type of an array from int to float.

Create a 1D array and reshape it to a 3x3 matrix.

Flatten a 2D array into a 1D array.

Get the sum of all elements in a NumPy array.

Get the maximum and minimum of an array.

Find the index of the maximum value in a 1D array.

Sort a NumPy array.

Copy an array using copy() method.

Create an array filled with a constant value.

Check if two NumPy arrays are equal.



Add, subtract, and multiply two arrays element-wise.

Perform matrix multiplication using @ operator.

Create a 6x6 matrix and extract the diagonal.

Calculate the mean, median, and standard deviation of an array.

Replace all elements greater than 5 in an array with 0.

Extract all odd numbers from an array.

Create a random array and round all values to 2 decimal places.

Stack two arrays vertically and horizontally.

Split an array into 3 equal parts.

Create a 3D array and access its individual layers.

Create a 2D array and find the row-wise and column-wise sum.

Generate a boolean array where values are True if even, False otherwise.

Create a 5x5 array with values 1,2,3,4 just below the diagonal.

Create a 5x5 array with 1 on the border and 0 inside.

Normalize a NumPy array (values between 0 and 1).

Count the number of non-zero elements in an array.

Create a checkerboard pattern 8x8 matrix.

Invert a matrix using NumPy.

Generate a 10x10 matrix and find its determinant.

Save a NumPy array to a .npy file and load it again.

Create a structured array with fields name (string), age (int), and marks (float).

Replace negative values in an array with 0 using np.where().

Calculate Euclidean distance between two arrays.

Create a 100-element array and count unique values and their frequencies.

Use broadcasting to subtract the mean of each column from a 2D array.

Tile a small 2x2 matrix to form an 8x8 matrix.

Replace the maximum value in an array with 0.

Mask an array where values are between 20 and 30.

Create a 5x5 matrix of random numbers and replace all even numbers with -1.

Compute the correlation coefficient between two 1D arrays.

In [1]:
#1. Create a 1D NumPy array of numbers from 0 to 9.

import numpy as np

array_1 = np.array ([1,2,3,4,5,6,7,8,9])
print(array_1)

[1 2 3 4 5 6 7 8 9]


In [2]:
#2. Create an array of 10 zeros.

array_2 = np.zeros(10)
print(array_2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#3. Create an array of 10 ones.

array_3 = np.ones(10)
print(array_3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#4. Create an array of 10 fives.

array_4 = np.ones(10)*5
print(array_4)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
#5. Create an array of even integers from 10 to 50.

array_5 = np.arange(10,51,2)
print(array_5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
#6. Create a 3x3 identity matrix.

array_6 = np.eye(3)
print(array_6)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#7. Generate an array of 20 linearly spaced numbers between 0 and 1.

array_7 = np.linspace(0,1,20)
print(array_7)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [8]:
#8. Create a 5x5 matrix with values from 1 to 25.

array_8 = np.arange(1,26).reshape(5,5)
print(array_8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [9]:
#9. Create a 5x5 matrix with values from 1 to 25.

array_9 = np.arange(1,26).reshape(5,5)
print(array_9)





[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [10]:
#10. Create a 3x3 matrix with random integers from 1 to 10.
import numpy as np
array_10 = np.random.randint(1,11,size=(3,3))
print(array_10)

[[ 3  5  9]
 [ 1  7  3]
 [ 3 10  3]]


In [11]:
#11. Get the shape and size of an array.

array_11 = np.array([[1,2,3],[4,5,6]])
shape = array_11.shape
size = array_11.size
print("Shape:", shape)
print("Size:", size)

Shape: (2, 3)
Size: 6


In [12]:
#12. Change the data type of an array from int to float.

array_12 = np.array(([1.5,2,3,4,5]), dtype=float)
print(array_12)

array_12.dtype

[1.5 2.  3.  4.  5. ]


dtype('float64')

In [13]:
#13. Create a 1D array and reshape it to a 3x3 matrix.

print("1D array 1 to 9 :")

array_13 = np.array([1,2,3,4,5,6,7,8,9])
print(array_13)

print("After Reshape to 3x3 matrix :")
print(array_13.reshape(3,3))


1D array 1 to 9 :
[1 2 3 4 5 6 7 8 9]
After Reshape to 3x3 matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#14. Flatten a 2D array into a 1D array.

array_14 = np.array([[1,2,3],[4,5,6]])
print(array_14)

print("Flatten a 2D array into a 1D array :")
print(array_14.flatten())

[[1 2 3]
 [4 5 6]]
Flatten a 2D array into a 1D array :
[1 2 3 4 5 6]


In [15]:
#15. Get the sum of all elements in a NumPy array.

array_15 = np.array([1,2,3,4,5,6,7,8,9])
print(array_15)

sum = np.sum(array_15)
print("Sum of all elements in a NumPy array :")
print(sum)

[1 2 3 4 5 6 7 8 9]
Sum of all elements in a NumPy array :
45


In [16]:
#16. Get the maximum and minimum of an array.
array_16 = np.array([1,2,3,4,5,6,7,8,9])
print(array_16)

max = np.max(array_16)
print("Maximum of an array :")
print(max)

min = np.min(array_16)
print("Minimum of an array :")
print(min)

[1 2 3 4 5 6 7 8 9]
Maximum of an array :
9
Minimum of an array :
1


In [17]:
#17. Find the index of the maximum value in a 1D array.

array_17 = np.array([1,2,3,4,5,6,7,8,9])
print(array_17)

#unable to solve

[1 2 3 4 5 6 7 8 9]


In [18]:
#18. Sort a NumPy array.

array_18 = np.array([5,4,6,2,6,3,6,3,2])
print(array_18)

print("Sort a NumPy array :")
print(np.sort(array_18))

[5 4 6 2 6 3 6 3 2]
Sort a NumPy array :
[2 2 3 3 4 5 6 6 6]


In [19]:
#19. Copy an array using copy() method.

array_19 = np.array([1,2,3,4,5,6,7,8,9])
print(array_19)

print("Copy an array using copy() method :")
print(array_19.copy())

[1 2 3 4 5 6 7 8 9]
Copy an array using copy() method :
[1 2 3 4 5 6 7 8 9]


In [20]:
#20. Create an array filled with a constant value.

array_20 = np.full((3,3),121)
print(array_20)



[[121 121 121]
 [121 121 121]
 [121 121 121]]


In [21]:
#21. Check if two NumPy arrays are equal.

array_21_1 = np.array([1,2,3,4,5,6,7,8,9])
array_21_2 = np.array([1,2,3,4,5,6,7,8,9])

print(np.equal(array_21_1,array_21_2))

[ True  True  True  True  True  True  True  True  True]


In [22]:
#22. Add, subtract, and multiply two arrays element-wise.

array_21_1 = np.array([1,2,3,4,5,6,7,8,9])
array_21_2 = np.array([1,2,3,4,5,6,7,8,9])

print(np.add(array_21_1,array_21_2))
print(np.subtract(array_21_1,array_21_2))
print(np.multiply(array_21_1,array_21_2))

[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64 81]


In [23]:
#23. Perform matrix multiplication using @ operator.

array_21_1 = np.array([1,2,3,4,5,6,7,8,9])
array_21_2 = np.array([1,2,3,4,5,6,7,8,9])

#print(np.@(array_21_1,array_21_2))

In [24]:
#24. Create a 6x6 matrix and extract the diagonal.

array_24 = np.arange(16).reshape(4,4)

print(array_24)

print("Extract the diagonal :")
print(np.diag(array_24))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extract the diagonal :
[ 0  5 10 15]


In [25]:
#25. Calculate the mean, median, and standard deviation of an array.

array_25 = np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(array_25))
print(np.median(array_25))
print(np.std(array_25))

5.0
5.0
2.581988897471611


In [26]:
#26 . Replace all elements greater than 5 in an array with 0.

array_26 = np.array([1,2,3,4,5,6,7,8,9])
array_26[array_26 > 5] =0
print(array_26)


[1 2 3 4 5 0 0 0 0]


In [27]:
#27. Extract all odd numbers from an array.

array_27 = np.array([1,2,3,4,5,6,7,8,9])
print(array_27)

print("Extract all odd numbers from an array :")
print(array_27[array_27 % 2 == 1 ])

[1 2 3 4 5 6 7 8 9]
Extract all odd numbers from an array :
[1 3 5 7 9]


In [28]:
#28. Create a random array and round all values to 2 decimal places.

array_28 = np.random.rand(3,3)
print(array_28)

print("Round all values to 2 decimal places :")
print(np.round(array_28,2))

[[0.53309235 0.36589908 0.11954041]
 [0.77002313 0.14331731 0.77223017]
 [0.81349429 0.60991055 0.20704084]]
Round all values to 2 decimal places :
[[0.53 0.37 0.12]
 [0.77 0.14 0.77]
 [0.81 0.61 0.21]]


In [29]:
#29. Stack two arrays vertically and horizontally.

array_29_1 = np.array([1,2,3,4,5,6,7,8,9])
array_29_2 = np.array([1,2,3,4,5,6,7,8,9])

print(np.vstack((array_29_1,array_29_2)))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [30]:
#30. Split an array into 3 equal parts.

array_30 = np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(array_30,3))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [31]:
#31. Create a 3D array and access its individual layers.

array_31 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_31)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
#32. Create a 2D array and find the row-wise and column-wise sum.

array_32 = np.array([[1,2,3],[4,5,6]])
print(array_32)

print("Row-wise sum :")
print(np.sum(array_32,axis=1))
print("Column-wise sum :")
print(np.sum(array_32,axis=0))

[[1 2 3]
 [4 5 6]]
Row-wise sum :
[ 6 15]
Column-wise sum :
[5 7 9]


In [33]:
#33. Generate a boolean array where values are True if even, False otherwise.

array_33 = np.array([1,2,3,4,5,6,7,8,9])
print(array_33)

print("Generate a boolean array where values are True if even, False otherwise :")
print(array_33 % 2 == 0)



[1 2 3 4 5 6 7 8 9]
Generate a boolean array where values are True if even, False otherwise :
[False  True False  True False  True False  True False]


In [34]:
#34. Create a 5x5 array with values 1,2,3,4 just below the diagonal.

array_34 = np.diag([1,2,3,4],k=-1)
print(array_34)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [35]:
#35. Create a 5x5 array with 1 on the border and 0 inside.

array_35 = np.ones((5,5))
array_35[1:-1,1:-1] = 0
print(array_35)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#36. Normalize a NumPy array (values between 0 and 1).

array_36 = np.array([1,2,3,4,5,6,7,8,9])
print(array_36)

print("Normalize a NumPy array (values between 0 and 1) :")
print((array_36 - np.min(array_36)) / (np.max(array_36) - np.min(array_36)))



[1 2 3 4 5 6 7 8 9]
Normalize a NumPy array (values between 0 and 1) :
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [37]:
#37 Count the number of non-zero elements in an array.

array_37 = np.array([1,2,3,4,5,6,7,8,9,0])
print(array_37)

print("Count the number of non-zero elements in an array :")
print(np.count_nonzero(array_37))

[1 2 3 4 5 6 7 8 9 0]
Count the number of non-zero elements in an array :
9


In [38]:
#38 Create a checkerboard pattern 8x8 matrix.

array_38 = np.zeros((8,8))
array_38[1::2,::2] = 1
array_38[::2,1::2] = 1
print(array_38)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [39]:
#39  Invert a matrix using NumPy.

array_39 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_39)

print("Invert a matrix using NumPy :")
#print(np.linalg.inv(array_39))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Invert a matrix using NumPy :


In [40]:
#40 .  Generate a 10x10 matrix and find its determinant.

array_40 = np.random.rand(10,10)
print(array_40)

print("Generate a 10x10 matrix and find its determinant :")
print(np.linalg.det(array_40))

[[0.42416149 0.30267487 0.06384855 0.88834627 0.61981799 0.21875686
  0.41687029 0.12189405 0.14272966 0.71014236]
 [0.47541532 0.48223145 0.81758201 0.45703077 0.1454138  0.46738595
  0.31095042 0.41048973 0.28508285 0.37585629]
 [0.59796841 0.80485824 0.88599526 0.07903592 0.98827315 0.86113547
  0.85299705 0.75430204 0.24658357 0.97748329]
 [0.8513905  0.6147975  0.80744984 0.71537187 0.16623065 0.81236928
  0.59116362 0.2364773  0.09828596 0.72697289]
 [0.16794106 0.43612254 0.58493618 0.357875   0.15093207 0.34967664
  0.77551454 0.39708832 0.09483675 0.70718905]
 [0.31301586 0.08221518 0.69599366 0.71048526 0.10500517 0.77247702
  0.6810507  0.94123066 0.96003818 0.52570913]
 [0.34260958 0.95644222 0.22488698 0.4146368  0.73409349 0.99510282
  0.87017286 0.51487545 0.76395826 0.76914109]
 [0.21663614 0.56850543 0.15854756 0.84972471 0.55183938 0.88204978
  0.41373668 0.4212567  0.51522503 0.13605711]
 [0.19485738 0.23662467 0.12589437 0.3751383  0.84040528 0.00476531
  0.87921138

In [41]:
#41 Save a NumPy array to a .npy file and load it again.

array_41 = np.array([1,2,3,4,5,6,7,8,9])
print(array_41)

print("Save a NumPy array to a .npy file and load it again :")
print(np.save("array_41.npy",array_41))
print(np.load("array_41.npy"))


[1 2 3 4 5 6 7 8 9]
Save a NumPy array to a .npy file and load it again :
None
[1 2 3 4 5 6 7 8 9]


In [42]:
#42 Create a structured array with fields name (string), age (int), and marks (float).

dt = np.dtype([('name', 'U20'), ('age', 'i4'), ('marks', 'f4')])

# Create the structured array with some sample data
students = np.array([
    ('ksn', 21, 85.5),
    ('superman', 22, 90.0),
    ('batman', 20, 72.3)
], dtype=dt)

# Print the structured array
print("Structured Array:")
print(students)

Structured Array:
[('ksn', 21, 85.5) ('superman', 22, 90. ) ('batman', 20, 72.3)]


In [43]:
#43 Replace negative values in an array with 0 using np.where().

array_43 = np.array([1,2,-3,4,-5,6,-7,8,-9])
print(array_43)

print("Replace negative values in an array with 0 using np.where() :")
print(np.where(array_43 < 0, 0, array_43))

[ 1  2 -3  4 -5  6 -7  8 -9]
Replace negative values in an array with 0 using np.where() :
[1 2 0 4 0 6 0 8 0]


In [44]:
#44 Calculate Euclidean distance between two arrays.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate Euclidean distance
distance = np.linalg.norm(a - b)

print("Euclidean Distance:", distance)

Euclidean Distance: 5.196152422706632


In [45]:
#45 Create a 100-element array and count unique values and their frequencies.

array_45 = np.random.randint(1, 11, size=100)

# Find unique values and their frequencies
unique_values, counts = np.unique(array_45, return_counts=True)

# Display results
print("Original Array:\n", array_45)
print("\nUnique Values:", unique_values)
print("Frequencies:", counts)

Original Array:
 [10 10  5 10  4  7  6 10  9  5  7  5  3  7  2  1  8  4  1  6  2  4  7  9
  4 10  8  8  7  8 10  2  4  6  2  2  3  9  4  9  6  7  2  2  9  9 10  2
  8  5  5  3  7  9  7  7  8  9  3  4  5  5 10  1  8  6  6  8  6  2  7 10
  1  5  2  6 10  3  9  5  4  8 10  9  3  7  2  5  4  5  5  2  7  7  9  8
  9  9  7  1]

Unique Values: [ 1  2  3  4  5  6  7  8  9 10]
Frequencies: [ 5 12  6  9 12  8 14 10 13 11]


In [46]:
#46 . Use broadcasting to subtract the mean of each column from a 2D array.

array_46 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

broad = array_46 - array_46.mean(axis=0)

print("Original Array:\n", array_46)
print("\nArray after Broadcasting:\n", broad)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after Broadcasting:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [47]:
#47. Tile a small 2x2 matrix to form an 8x8 matrix.

small_matrix = np.array([[1, 2], [3, 4]])

big_matrix = np.tile(small_matrix, (4, 4))

print("Small Matrix:\n", small_matrix)
print("\nBig Matrix (after tiling):\n", big_matrix)

Small Matrix:
 [[1 2]
 [3 4]]

Big Matrix (after tiling):
 [[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


In [48]:
#48.  Replace the maximum value in an array with 0.

array_48 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find the index of the maximum value
max_index = np.argmax(array_48)

# Replace the maximum value with 0
array_48[max_index] = 0

print("Original Array:\n", array_48)


Original Array:
 [1 2 3 4 5 6 7 8 0]


In [49]:
# 49 .Mask an array where values are between 20 and 30.

array_49 = np.array([10,21,24,26,25,29,30,32])
mask = (array_49 >= 20) & (array_49 <= 30)
array_49[mask] = 0
print(array_49)

[10  0  0  0  0  0  0 32]


In [50]:
#50 . Create a 5x5 matrix of random numbers and replace all even numbers with -1.

array_50 = np.random.randint(1, 101, size=(5, 5))
print(array_50)

# Replace even numbers with -1
array_50[array_50 % 2 == 0] = -1

print("Evenly replaced Matrix:\n", array_50)

[[100  43  88  99  27]
 [ 54  67  51  43  62]
 [ 91  84  95  64  12]
 [ 47  23   4  49  33]
 [ 71  26  13  67  88]]
Evenly replaced Matrix:
 [[-1 43 -1 99 27]
 [-1 67 51 43 -1]
 [91 -1 95 -1 -1]
 [47 23 -1 49 33]
 [71 -1 13 67 -1]]





Calculate Euclidean distance between two arrays.

Create a 100-element array and count unique values and their frequencies.

Use broadcasting to subtract the mean of each column from a 2D array.

Tile a small 2x2 matrix to form an 8x8 matrix.

Replace the maximum value in an array with 0.

Mask an array where values are between 20 and 30.

Create a 5x5 matrix of random numbers and replace all even numbers with -1.

Compute the correlation coefficient between two 1D arrays.
